version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80" 
    volumes:
        - ./milanesapp:/src/milanesapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: sleep infinity
